-- INSERT INTO board (board_name)
-- VALUES ('전체 게시판'),
--        ('자유 게시판'),
--        ('개발 게시판'),
--        ('일상 게시판'),
--        ('사건사고 게시판');
--
-- INSERT INTO article (board_id, id, password, content, title)
-- VALUES  (2, 1, 1111, '꾸준한 블로그 정리', 'Spring Boot 공부방법 공유'),
--         (3, 2, 2222, 'GCP, NCP, AWS 비교', 'devOps 플랫폼별 장단점'),
--         (4, 3, 3333, '포트폴리오 완성하기', '2024 목표'),
--         (5, 4, 4444, '어렵다...', 'MVC 패턴 미숙함 이슈'),
--         (3, 5, 6666, 'GET 은 조회하기, POST 는 전송하기', 'GET vs POST');
--
--

-- 따로 따로 실행해야 함.
